apiVersion: apps/v1
kind: Deployment
metadata:
  name: pre-run
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: pre-run
  template:
    metadata:
      labels:
        app: pre-run
    spec:
      containers:
      - name: pre-run
        image: mcsheltonomondi/pre-run
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3122
